imports:
- path: vm-template.py

resources:
- name: template-deploy
  type: vm-template.py
  properties:
    # required
    machineType: g1-small
    sourceImage: projects/centos-cloud/global/images/centos-7-v20180716
    network: my-vpc
    zones:
    - us-west1-a
    - us-west2-a
    - us-east1-b
    # optional
    tags:
    - todd
    - private
